version: '3.8'

services:
  update-server:
    image: nginx:stable-alpine
    container_name: gotoim-update-server
    ports:
      - "7755:80"
    volumes:
      # - ./dev-app-update.yml:/usr/share/nginx/html/auto-updates/dev-app-update.yml:ro
      - ./dist:/usr/share/nginx/html/auto-updates:ro
      - ./docker/nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
